name: testws

channels:
  - pytorch

dependencies:
  - python=3.7
  - pytorch
  - click
  - pip:
    - numpy==1.21
    - imageio==2.19
    - chainercv==0.13
    - git+https://github.com/lucasb-eyer/pydensecrf.git
    - scikit-image

    - joblib
    - omegaconf
    - tensorflow
    - torchnet
    - opencv-python

    - gdown
    
    - cython==0.29.30
    
    - pycocotools==2.0.4
    - scikit-image==0.19.3
    - torchvision==0.12.0