name: testws

dependencies:
  - python=3.7.13
  - pytorch==1.1.0

  - pip
  - pip:
    - chainercv==0.13.1
    - cython==0.29.30
    - imageio
    - pycocotools==2.0.4
    - scikit-image==0.19.3
    - torchvision==0.12.0
    - git+https://github.com/lucasb-eyer/pydensecrf.git